# Development-specific configurations
server:
  port: 8081  # Sử dụng cổng 8081 thay vì 8080 để tránh xung đột

spring:
  # Database Configuration  
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  
  # JPA Configuration  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
  
  # Kafka Configuration - disabled in development
  kafka:
    enabled: false
  
  # Flyway Configuration - disabled in development for now
  flyway:
    enabled: false
  
  # Enable development tools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    '[com.learning.reelnet]': DEBUG
    '[org.hibernate.SQL]': DEBUG

# Auth0 development configuration
auth0:
  domain: dev-og4gg3ghvjxtwo22.us.auth0.com
  audience: dev-og4gg3ghvjxtwo22.us.auth0.com/api/v2/
  client-id: XpSryAbP6XqOfjAoHmVsJc6ZDVaA7upR
  client-secret: ccM53jvwx6nCakr-kr8KxAWV_5ssvq9HFK2Bn4vghaHdhXx2O1aeiQnJKhPRmnMz

